/datum/map/wyrm

	apc_test_exempt_areas = list(
		/area/space = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/science/xenoflora_storage = NO_SCRUBBER|NO_VENT,
		/area/engineering/extsubmaint = NO_SCRUBBER,
		/area/maintenance/construction = NO_APC,
		/area/engineering/teg = NO_SCRUBBER|NO_VENT,
		/area/engineering/externalmaint = NO_SCRUBBER,
		/area/engineering/atmos = NO_SCRUBBER,
		/area/maintenance/primary/fp = NO_SCRUBBER|NO_VENT,
		/area/pod/start = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/engp = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/engineering/atmosmon = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/med = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/fs = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/sec = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/engs = NO_SCRUBBER|NO_VENT,
		/area/maintenance/primary/cargo = NO_SCRUBBER|NO_VENT,
		/area/holodeck = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/turbolift/freightsub = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/turbolift/freightmain = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/rescue/start = NO_SCRUBBER,
		/area/exoplanet          = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/desert   = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/grass    = NO_SCRUBBER|NO_VENT|NO_APC,
		/area/exoplanet/snow     = NO_SCRUBBER|NO_VENT|NO_APC,
	)
